from .Categories_view import categories_view
from .index_view import index_view
from .category_view import category_view
from .stripe_view import create_checkout_session
from .payment_cancel import payment_cancel
from .payment_success import payment_success
from .cart_view import create_order
from .user_orders_view import user_orders_view
from .contact_view import contact_view
from .about_view import about_view
