# Generated by Django 5.1.5 on 2025-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_order_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pick_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
