# Generated by Django 5.0.6 on 2025-03-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_category_product_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_nl',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nl',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_nl',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
