# Generated by Django 5.0.6 on 2025-03-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_description_fr_category_description_nl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='description_fr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_nl',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_nl',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_nl',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fr',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_nl',
            field=models.CharField(default='', max_length=60),
        ),
    ]
