# Generated by Django 5.0.6 on 2025-03-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cookieconsent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CookieConsent',
        ),
    ]
